In [6]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
import pandas as pd

In [14]:
np.array([1,2,3])


array([1, 2, 3])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.full((5,2),(3,5)) #We can define the column and the row nubers with the values here

array([[3, 5],
       [3, 5],
       [3, 5],
       [3, 5],
       [3, 5]])

In [25]:
x = np.full((10,20),1)
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [26]:
x.ndim # Check the dimensions of an array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
x.shape # check the shape of array

(10, 20)

In [28]:
x.size #check the size (total number of items)

200

In [29]:
x.dtype # Check the datatype

dtype('int32')

In [30]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  
# 1-dimensional array
print("Number of dimensions: ", x1.ndim)
print("Shape: ", x1.shape)
print("Size: ", x1.size)
print("Type: ", x1.dtype)

Number of dimensions:  1
Shape:  (6,)
Size:  6
Type:  int32


In [34]:
x[0,1]
x[0,1] = 3 #to access one element in an array converts to intt
x


array([[1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [35]:
y = np.random.randint(10, size=6)
y

array([8, 8, 1, 6, 7, 7])

In [36]:
y[0:3] # returns the specified range of elements
y[:2]
y[0::2] #start with the first element and third ans increase by 2
y

array([8, 8, 1, 6, 7, 7])

In [37]:
a = np.array([1,2,3])
b = np.array([3,2,1])
np.concatenate([a,b])

array([1, 2, 3, 3, 2, 1])

In [38]:
z = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])
np.vstack([z, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [39]:
def calculate_inverse(values):    
    output = np.empty(len(values))    
    for i in range(len(values)):        
        output[i] = 1.0 / values[i]    
    return output       

values = np.random.randint(1, 10, size=5)
print(calculate_inverse(values))

large_array = np.random.randint(1, 100, size=1000000)

# This is a Jupyter notebook tool to measure the execution
# time of an instruction
%timeit calculate_inverse(large_array)

[0.11111111 0.5        0.16666667 0.11111111 0.2       ]
1.63 s ± 98.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [40]:
%timeit (1.0 / large_array) # NumPy option takes less time

2.69 ms ± 37.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [41]:
x = [-2, -1, 1, 2]

print("Absolute value: ", np.abs(x))
print("Exponential: ", np.exp(x))
print("Logarithm: ", np.log(np.abs(x)))

Absolute value:  [2 1 1 2]
Exponential:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithm:  [0.69314718 0.         0.         0.69314718]


In [42]:
x = np.random.rand(3,3)
x > 0.5
#np.where(x > 0.5)

array([[ True,  True, False],
       [ True,  True,  True],
       [False,  True, False]])

In [48]:
L = np.random.randint(9999989)
np.sum(L)

3943341

In [49]:
%timeit sum(large_array)
%timeit np.sum(large_array)

49.8 ms ± 1.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
333 µs ± 91.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [50]:
M = np.random.random((3, 4))
print(M)
# Note the syntax variable.function instead of 
# np.fonction(variable). Both are acceptable if
# variable is a Numpy array.
print("Sum of all elements of M: ", M.sum())
print("Sums of the columns of M: ", M.sum(axis=0))

[[0.468866   0.87884932 0.09785878 0.12446372]
 [0.42253024 0.39034562 0.35621026 0.99663284]
 [0.55823601 0.84371046 0.78986544 0.99105381]]
Sum of all elements of M:  6.9186224847093705
Sums of the columns of M:  [1.44963224 2.11290539 1.24393448 2.11215037]


In [51]:
np.std(M)
np.argmin
np.percentile

<function numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None)>

In [52]:
x = np.random.rand(3,3)
x > 0.5
np.where(x > 0.5)

(array([0, 1, 1, 2, 2], dtype=int64), array([2, 0, 2, 1, 2], dtype=int64))

In [53]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b
a + 5

array([5, 6, 7])

In [54]:
M = np.ones((3, 3))
print("M is: \n", M)
print("M+a is: \n", M+a)

M is: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
M+a is: 
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
